//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessBourneV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressTable
    {
        public int Adr_Id { get; set; }
        public double Adr_Lat { get; set; }
        public double Adr_Long { get; set; }
        public string Adr_Unit_No { get; set; }
        public string Adr_House_No { get; set; }
        public string Adr_Street_Name { get; set; }
        public string Adr_Suburb_Name { get; set; }
        public string Adr_City_Name { get; set; }
        public string Adr_Zipcode { get; set; }
        public string Adr_State_Name { get; set; }
        public string Adr_FullAddress { get; set; }
    
        public virtual FitnessClub FitnessClub { get; set; }
        public virtual MemberTable MemberTable { get; set; }
        public virtual LocationTable LocationTable { get; set; }
    }
}
