//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessBourneV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventMembers
    {
        public int EvMem_Id { get; set; }
        public bool EvMem_IsConfirmed { get; set; }
    
        public virtual EventTable EventTable { get; set; }
        public virtual MemberTable MemberTable { get; set; }
    }
}
