//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessBourneV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EventTable()
        {
            this.LocationTables = new HashSet<LocationTable>();
        }
    
        public int Evnt_Id { get; set; }
        public byte Evnt_Is_Private { get; set; }
        public System.DateTime Evnt_Start_DateTime { get; set; }
        public System.DateTime Evnt_End_DateTime { get; set; }
        public byte Evnt_Is_Checkd_In { get; set; }
        public int Evnt_Capacity { get; set; }
        public int EventTypeET_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocationTable> LocationTables { get; set; }
        public virtual MemberTable Admin { get; set; }
        public virtual EventEdit EventEdit { get; set; }
        public virtual EventType EventType { get; set; }
        public virtual FitnessClub FitnessClub { get; set; }
    }
}
