//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessBourneV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventEdit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EventEdit()
        {
            this.LocationTables = new HashSet<LocationTable>();
        }
    
        public int EE_Id { get; set; }
        public System.DateTime EE_DateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocationTable> LocationTables { get; set; }
        public virtual NotificationTable NotificationTable { get; set; }
        public virtual MemberTable Creator { get; set; }
        public virtual EventTable EventTable { get; set; }
    }
}
