//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessBourneV2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fbmodelContainer : DbContext
    {
        public fbmodelContainer()
            : base("name=fbmodelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FitnessClub> FitnessClubs { get; set; }
        public virtual DbSet<AddressTable> AddressTables { get; set; }
        public virtual DbSet<MemberTable> MemberTables { get; set; }
        public virtual DbSet<EventTable> EventTables { get; set; }
        public virtual DbSet<NotificationActionTable> NotificationActionTables { get; set; }
        public virtual DbSet<NotificationTable> NotificationTables { get; set; }
        public virtual DbSet<EventEdit> EventEdits { get; set; }
        public virtual DbSet<LocationTable> LocationTables { get; set; }
        public virtual DbSet<EventType> EventTypes { get; set; }
        public virtual DbSet<EventMembers> EventMembers { get; set; }
    }
}
