//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessBourneV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FitnessClub
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FitnessClub()
        {
            this.MemberTables = new HashSet<MemberTable>();
        }
    
        public int FC_Id { get; set; }
        public string FC_Ref_Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberTable> MemberTables { get; set; }
        public virtual AddressTable AddressTable { get; set; }
    }
}
