//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessBourneV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberTable
    {
        public int Mem_Id { get; set; }
        public string Mem_Contact_No { get; set; }
        public string Mem_Email_Id { get; set; }
        public int FitnessClubFC_Id { get; set; }
        public string Mem_FirstName { get; set; }
        public string Mem_GivenName { get; set; }
    
        public virtual FitnessClub FitnessClub { get; set; }
        public virtual EventTable EventAdmin { get; set; }
        public virtual NotificationActionTable NotificationActionTable { get; set; }
        public virtual EventEdit EventEdited { get; set; }
        public virtual AddressTable AddressTable { get; set; }
    }
}
