//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessBourneV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MemberTable()
        {
            this.EventMembers = new HashSet<EventMembers>();
            this.EventTables = new HashSet<EventTable>();
        }
    
        public int Mem_Id { get; set; }
        public string Mem_Contact_No { get; set; }
        public string Mem_Email_Id { get; set; }
        public int FitnessClubFC_Id { get; set; }
        public string Mem_FirstName { get; set; }
        public string Mem_GivenName { get; set; }
    
        public virtual FitnessClub FitnessClub { get; set; }
        public virtual NotificationActionTable NotificationActionTable { get; set; }
        public virtual EventEdit EventEdited { get; set; }
        public virtual AddressTable AddressTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventMembers> EventMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventTable> EventTables { get; set; }
    }
}
