//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessBourneV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationActionTable
    {
        public int NA_Id { get; set; }
        public string NA_Decision { get; set; }
        public int NotificationTableNotif_Id { get; set; }
    
        public virtual NotificationTable NotificationTable { get; set; }
        public virtual MemberTable MemberTable { get; set; }
    }
}
