//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessBourneV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NotificationTable()
        {
            this.NotificationActionTables = new HashSet<NotificationActionTable>();
        }
    
        public int Notif_Id { get; set; }
        public string Notif_Type { get; set; }
        public string Notif_Message { get; set; }
    
        public virtual EventEdit EventEdit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationActionTable> NotificationActionTables { get; set; }
    }
}
